apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 1m
  chart:
    spec:
      chart: redis
      version: "17.11.7" # Specify your desired version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Add your specific configuration values here
    architecture: replication  # Changed from standalone to replication
    auth:
      enabled: true
      password: "password"
    master:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
    replica:
      replicaCount: 4  
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
